#+TITLE: Pamparam - Flash Cards
#+AUTHOR: Roger J. H. Welsh
#+EMAIL: rjhwelsh@gmail.com

* Flashcards with Pamparam
Pamparam is a spaced repetition (SR) memory cards implementation for Emacs.
See https://github.com/abo-abo/pamparam for details.
** Config
Have all keybindings in one place with a "hydra".
https://github.com/abo-abo/hydra

#+BEGIN_SRC emacs-lisp
(global-set-key (kbd "C-c m") 'hydra-pamparam/body)
#+END_SRC

Setup flashcard repos into separate directories.
This example is no different from the default behaviour.
#+BEGIN_EXAMPLE emacs-lisp
(setq pamparam-alist '(
    ("~/.emacs.d/flashcards.org" . "~/.emacs.d/flashcards.pam")
)
)
#+END_EXAMPLE

** Keybindings
Card file
| key | description                  |
|-----+------------------------------|
| .   | pamparam-card-validate-maybe |
| n   | pamparam-drill               |
| q   | bury-buffer                  |
| R   | pamparam-card-redo           |
| D   | pamparam-card-delete         |

Master file
=pamparam-sync=

Anywhere in the repo
=pamparam-drill=
=pamparam-pull=
=pamparam-commit=

** Creating Flashcards

#+BEGIN_EXAMPLE
 * Cards            :cards:
 ** comic story
het stripverhal
 *** The Adventures of Tintin is a world famous Belgian comic strip.
De Avonturen van Kuifje is een wereldbekend Belgisch stripverhaal.

 ** singer
de zanger
de zangeres
 *** The singer is only know on in Belgium.
De zangeres is alleen in België bekend.
#+END_EXAMPLE

Card sources are tagged with =:cards:=.
A seperate card file is created for each second/third level outline child of
each card source. In the example above 4 cards will be created.

For each of the "card" outlines, the *heading* will be the question and the
*body* will be the answer.

Multiple correct answers may be placed underneath a heading. Each line
underneath a *heading* corresponds to an alternative response.

Call =pamparam-sync= to synchronize the =org= file with your =pamparam= repo.

** Drilling
	To drill yourself on cards the general procedure is.
	| Step | Key     | Command         | Description                                       |
	|    1 | C-c m s | pamparam-sync   | Synchronized the org-file with the pamparam pile. |
	|    2 | C-c m d | pamparam-drill  | Resumes / Starts drilling with cards.             |
	|    3 | C-c m c | pampered-commit | Commit your progress to the pile.                 |
	|    4 | C-c m p | pamparam-pull   | Pull more cards out from the pile for drilling.   |
	|    5 | C-c m q | quit (cancel)   | Cancels the command that would have been made.    |
	|      |         |                 |                                                   |
