#+TITLE: Thematic configuration
#+AUTHOR: Roger J. H. Welsh
#+EMAIL: rjhwelsh@gmail.com

* Harry's UI preferences
N.B. All of this was taken from Harry Schwartz's configuration.org.
**** Tweak window chrome
I don't usually use the menu or scroll bar, and they take up useful space.
#+BEGIN_SRC emacs-lisp
  (tool-bar-mode 0)
  (menu-bar-mode 0)
  (when window-system
    (scroll-bar-mode -1))
#+END_SRC

**** Use fancy lambdas
Why not?
#+BEGIN_SRC emacs-lisp
  (global-prettify-symbols-mode t)
#+END_SRC

**** Custom theme
If this code is being evaluated by =emacs --daemon=, ensure that each subsequent
frame is themed appropriately.
#+BEGIN_SRC emacs-lisp
	(require 'solarized-theme)
	(if (daemonp)
			(add-hook 'after-make-frame-functions
								(lambda (frame)
									(hrs/apply-theme)))
		(hrs/apply-theme))
#+END_SRC

**** Disable visual bell
=sensible-defaults= replaces the audible bell with a visual one, but I really
don't even want that (and my Emacs/Mac pair renders it poorly). This disables
the bell altogether.

#+BEGIN_SRC emacs-lisp
  (setq ring-bell-function 'ignore)
#+END_SRC

**** Scroll conservatively
When point goes outside the window, Emacs usually recenters the buffer point.
I'm not crazy about that. This changes scrolling behavior to only scroll as far
as point goes.

#+BEGIN_SRC emacs-lisp
  (setq scroll-conservatively 100)
#+END_SRC

**** Highlight the current line
=global-hl-line-mode= softly highlights the background color of the line
containing point. It makes it a bit easier to find point, and it's useful when
pairing or presenting code.

#+BEGIN_SRC emacs-lisp
  (when window-system
    (global-hl-line-mode))
#+END_SRC
