#+TITLE: EMACS configuration
#+AUTHOR: Roger J. H. Welsh
#+EMAIL: rjhwelsh@gmail.com
#+PROPERTY: header-args    :results silent
#+STARTUP: content

* Introduction
Originally inspired by Harry R. Schwartz. Your excellent introduction to
org-mode has inspired this.
* Harry's sensible-defaults.el
You can find this file, [[https://github.com/hrs/sensible-defaults.el][here]].
#+BEGIN_SRC emacs-lisp
(load-file "~/.emacs.d/sensible-defaults.el")
(sensible-defaults/use-all-settings)
(sensible-defaults/use-all-keybindings)
#+END_SRC

* Personal Details
I would like to be able to share my config with other people to ease their
journey into emacs, as many others examples have done for me.
At the same time I would like to keep personal information private, so I source
a separate personal.org file, which is not included my repository.
#+BEGIN_SRC emacs-lisp
(org-babel-load-file "~/.emacs.d/personal.org")
#+END_SRC
.
* Init.el Comments
The following is commented out (as examples) , because it is required in the
init.el file; such that the latest version of org can be loaded before this file
is executed itself by *org*.

The package library is required for package management.
#+BEGIN_EXAMPLE emacs-lisp
 (require 'package)
#+END_EXAMPLE

Disable automatic package loading.
#+BEGIN_EXAMPLE emacs-lisp
 (setq package-enable-at-startup nil)
 (package-initialize)
#+END_EXAMPLE

This code provides a source list of package archives, from which to install packages.
#+BEGIN_EXAMPLE emacs-lisp
 (add-to-list 'package-archives '("org" . "http://orgmode.org/elpa/"))
 (add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/"))
 (add-to-list 'package-archives '("melpa-stable" . "http://stable.melpa.org/packages/"))
#+END_EXAMPLE

Refresh the last view of the elisp archives.
#+BEGIN_EXAMPLE emacs-lisp
 (unless package-archive-contents
   (package-refresh-contents))
(setq package-load-list '(all))
#+END_EXAMPLE

Use-package is a special set of macros to automatically install and
load packages from the init.el file, this needs to be
"bootstrapped" before we can use it.
#+BEGIN_EXAMPLE emacs-lisp
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))
(eval-when-compile
  (require 'use-package))
(require 'bind-key)
(require 'diminish)
#+END_EXAMPLE

Org-mode is required for evaluating code-blocks via babel.
#+BEGIN_EXAMPLE emacs-lisp
(require 'org)
#+END_EXAMPLE

This ensures emacs always follows symlinks to the version-controlled source.
#+BEGIN_EXAMPLE emacs-lisp
(setq vc-follow-symlinks t)
#+END_EXAMPLE

Load the main-configuration file. "Literally this file".
#+BEGIN_EXAMPLE emacs-lisp
(org-babel-load-file "~/.emacs.d/configuration.org")
#+END_EXAMPLE

* Hide certain modes from the modeline

*Harry:* I'd rather have only a few necessary mode identifiers on my modeline.
This either hides or "renames" a variety of major or minor modes using the
=diminish= package.

I use Harry's macros for completeness. If a package is setup with =use-package=,
please use the =:diminish= option there instead.

#+BEGIN_SRC emacs-lisp
  (defmacro diminish-minor-mode (filename mode &optional abbrev)
    `(eval-after-load (symbol-name ,filename)
       '(diminish ,mode ,abbrev)))

  (defmacro diminish-major-mode (mode-hook abbrev)
    `(add-hook ,mode-hook
               (lambda () (setq mode-name ,abbrev))))

  (diminish-minor-mode 'abbrev 'abbrev-mode)
  (diminish-minor-mode 'simple 'auto-fill-function)
  (diminish-minor-mode 'subword 'subword-mode)
  (diminish-minor-mode 'undo-tree 'undo-tree-mode)
  (diminish-major-mode 'emacs-lisp-mode-hook "el")
  (diminish-major-mode 'lisp-interaction-mode-hook "λ")
  (diminish-major-mode 'python-mode-hook "Py")
#+END_SRC

* Auto-compile
Always compile packages and use the newest available.
#+BEGIN_SRC emacs-lisp
(use-package auto-compile
  :config (auto-compile-on-load-mode)
  :ensure t)
(setq load-prefer-newer t)
#+END_SRC

* Load configuration methods
All of these use =use-package= to install packages, with the =:ensure t= option.
If you are loading this for the first time, make sure you have an internet
connection.

When I use Emacs, I typically load an emacs server (=emacs --daemon=), and edit
files using =emacsclient -c=. This loads a new frame for each file I edit. If I
am already inside emacs, I will use =C-x C-f= to find a file and load it.

If you are new to emacs, (like I was) my process to start off was:
 * I started off with the tutorial =C-h t=.
 * I moved on to the [[info:info][*info*]] tutorial =C-h i=. The *info* pages are super
   helpful, and easy to navigate once you learn how.
 * Then I spent weeks crafting my configuration to get the setup I wanted,
   typically most of this was spent on configuring org and reading info pages.

This sets the local-config-dir.
#+BEGIN_SRC emacs-lisp
	(setq rjh/local-config-dir
				(expand-file-name
				 "config"
				 rjh/local-config-repo ))
#+END_SRC

This function will load a single configuration file.
#+BEGIN_SRC emacs-lisp
	(defun rjh/load-config (pkg_a)
		(org-babel-load-file
		 (expand-file-name pkg_a rjh/local-config-dir)))
#+END_SRC

* eVil
The emacs VI interface layer.
For those who prefer the feel of Vi on emacs.
#+BEGIN_SRC emacs-lisp
	(use-package evil
		:ensure t)
#+END_SRC

* Org
To see the complete org configuration, see [[file:config/org.org][org.org]].
#+BEGIN_SRC emacs-lisp
	(rjh/load-config "org.org" )
	(rjh/load-config "org-gantt.org" )
#+END_SRC

Add pretty bullets for org-mode.
#+BEGIN_SRC emacs-lisp
	(use-package "org-bullets" :ensure t )
#+END_SRC

Emacs speaks statistics package.
#+BEGIN_SRC emacs-lisp
	(use-package "ess" :ensure t)
	(require 'ess-site)
#+END_SRC

Emacs org-caldav package for calendar integration.
#+BEGIN_SRC emacs-lisp
	(use-package "org-caldav" :ensure t)
#+END_SRC

* Yasnippet
Yasnippet provides a templating engine for Emacs.
For more, see [[file:config/yasnippet.org][yasnippet.org]].
N.B. For html tags use emmet-mode instead of yasnippet.
#+BEGIN_SRC emacs-lisp
	(use-package popup :ensure t)
	(use-package "yasnippet"
		:ensure t
		:diminish yas-minor-mode
		:init
		(require 'yasnippet)
		(yas-global-mode 1) ; enable globally
		:config
		(rjh/load-config "yasnippet.org"))
	(use-package "yasnippet-snippets" :ensure t) ;; Official snippets by AndreaCrotti
#+END_SRC

* Company
Company-mode provides auto-completion features for many other modes.

Company mode has some compatibility issues with yasnippet.
For more see [[file:config/company.org::*Yasnippet%20compatibility][Yasnippet compatibility]].

#+BEGIN_SRC emacs-lisp
	(use-package company
		:ensure t
		:diminish company-mode
		:init
		(setq company-global-modes t)
		(global-company-mode 1)
		(setq company-idle-delay 0.8)
		(setq company-minimum-prefix-length 2)
		(rjh/load-config "company.org"))
#+END_SRC

* Helm
Helm is an incremental completion and selection narrowing framework for Emacs.
https://emacs-helm.github.io/helm/
http://tuhdo.github.io/helm-intro.html
#+BEGIN_SRC emacs-lisp
	(use-package helm
		:ensure t
		:init
		(require 'helm)
		(require 'helm-config)
		(global-unset-key (kbd "C-x c"))
		(setq helm-split-window-in-side-p           t ; open helm buffer inside current window, not occupy whole other window
					helm-move-to-line-cycle-in-source     t ; move to end or beginning of source when reaching top or bottom of source.
					helm-ff-search-library-in-sexp        t ; search for library in `require' and `declare-function' sexp.
					helm-scroll-amount                    8 ; scroll 8 lines other window using M-<next>/M-<prior>
					helm-ff-file-name-history-use-recentf t
					helm-echo-input-in-header-line t
					helm-autoresize-max-height 0
					helm-autoresize-min-height 20)
		(helm-autoresize-mode 1)
		(helm-mode 1)
		:bind
		(("C-c h" . helm-command-prefix)
		 ("M-x" . helm-M-x)
		 ("C-x C-f" . helm-find-files)
		 ("C-x M-f" . helm-recentf)
		 ("C-x b" . helm-mini)
		 ("M-y" . helm-show-kill-ring)
		 :map helm-map
		 ("<tab>" . helm-execute-persistent-action)
		 ("C-i" . helm-execute-persistent-action)
		 ("C-z" . helm-select-action)))
#+END_SRC
* Latex
Latex configuration.
For more see [[file:config/latex.org][latex.org]].
#+BEGIN_SRC emacs-lisp
	(rjh/load-config "latex.org")
#+END_SRC

* Graph
Some packages for graphing.
#+BEGIN_SRC emacs-lisp
	(use-package "gnuplot" :ensure t )
	(use-package "graphviz-dot-mode" :ensure t )
#+END_SRC

* UML
Plantuml for uml diagramming.
PlantUML is a java program for quickly constructing uml diagrams.
http://plantuml.com/
https://github.com/skuro/plantuml-mode

Flycheck is used for syntax checking.
https://github.com/alexmurray/flycheck-plantuml

#+BEGIN_SRC emacs-lisp
	(use-package "plantuml-mode" :ensure t
		:init
		(setq plantuml-jar-path "/usr/share/plantuml/lib/plantuml.jar")
		(add-to-list 'auto-mode-alist '("\\.plantuml$" . plantuml-mode))
		(add-to-list
		 'org-src-lang-modes '("plantuml" . plantuml))
		(setq org-plantuml-jar-path plantuml-jar-path)
		:config
		(plantuml-set-output-type "svg"))

	(use-package "flycheck-plantuml"
    :requires flycheck plantuml-mode
		:init
		(with-eval-after-load 'flycheck
			(require 'flycheck-plantuml)
			(flycheck-plantuml-setup))
		:ensure t)
#+END_SRC

* Git
I use =magit= for git integration.
The following key-bindings are for global convenience.
Use =C-x g ?= to get a quick command listing.
#+BEGIN_SRC emacs-lisp
	(use-package magit
		:ensure t
		:pin melpa-stable
		:bind (("C-x g" . magit-status)
					 ("C-x M-g" . magit-dispatch-popup)))
#+END_SRC

Git time-machine provides a mode for traversing the git history of a file.
Use =M-x git-timemachine=, =np= to navigate and =q= to quit.
#+BEGIN_SRC emacs-lisp
	(use-package "git-timemachine" :ensure t )
#+END_SRC

* Java
JDEE - Java Development Environment for Emacs

The jdee-server should be installed on your system, if it isn't please use the
following link to install the latest version. [[https://github.com/jdee-emacs/jdee-server][jdee-server@github]].
Jdee-server depends on Maven-3.

Setup jdee to use the following server directory, =~/.emacs.d/jdee-server/target=.
This is configurable in personal.org.

Use =M-x jdee-mode= to invoke jdee.

For more documentation, please see http://jdee.sourceforge.net/jdedoc/html/jde-ug/jde-ug.html
#+BEGIN_SRC emacs-lisp
	(use-package "jdee"
		:ensure t
		:config
		(setq jdee-global-classpath '("."))) ;; Use the current working directory as a classpath for java projects.
#+END_SRC

* Python
The Emacs Python Development Environment. This is a full featured environment
for python development. For introspection and analysis of Python sources, Elpy
mainly relies on Jedi. Jedi is known to have some problems coping with
badly-formatted Python.

For more see [[file:config/python.org][python.org]].

#+BEGIN_SRC emacs-lisp
	(use-package "elpy"
		:ensure t
		:init
		(elpy-enable)
		(setq python-indent 2)
		:config
		(rjh/load-config "python.org"))
#+END_SRC

#+BEGIN_SRC emacs-lisp
	(use-package "company-jedi"
		:requires company
		:ensure t)
#+END_SRC

* Irony                                                      :DISABLED:Cpp:C:
This configuration is taken from [[http://martinsosic.com/development/emacs/2017/12/09/emacs-cpp-ide.html][Martin Sosic]].
https://github.com/Sarcasm/irony-mode

For more see [[file:config/irony.org][irony.org]].
#+BEGIN_SRC emacs-lisp
	(use-package irony
	  :disabled
		:ensure t
		:config
		(progn
			;; If irony server was never installed, install it.
			(unless (irony--find-server-executable)
				(call-interactively #'irony-install-server))
			(add-hook 'c++-mode-hook 'irony-mode)
			(add-hook 'c-mode-hook 'irony-mode)
			;; Use compilation database first, clang_complete as fallback.
			(setq-default irony-cdb-compilation-databases
										'(irony-cdb-libclang
											irony-cdb-clang-complete))
			(add-hook 'irony-mode-hook 'irony-cdb-autosetup-compile-options)))
#+END_SRC
#+BEGIN_SRC emacs-lisp
	;; I use irony with company to get code completion.
	(use-package company-irony
		:requires company irony
		:ensure t
		:config
		(progn
			(eval-after-load 'company
				'(add-to-list 'company-backends 'company-irony))))
#+END_SRC
#+BEGIN_SRC emacs-lisp
	;; I use irony with flycheck to get real-time syntax checking.
	(use-package flycheck-irony
		:requires flycheck irony
		:ensure t
		:config
		(progn
			(eval-after-load 'flycheck
				'(add-hook 'flycheck-mode-hook #'flycheck-irony-setup))))
#+END_SRC
#+BEGIN_SRC emacs-lisp
	;; Eldoc shows argument list of the function you are currently writing in the echo area.
	(use-package irony-eldoc
		:requires eldoc irony
		:ensure t
		:config
		(progn
			(add-hook 'irony-mode-hook #'irony-eldoc)))
#+END_SRC

* Rtags                                                               :Cpp:C:
 This configuration is taken from [[http://martinsosic.com/development/emacs/2017/12/09/emacs-cpp-ide.html][Martin Sosic]].
 https://github.com/Andersbakken/rtags
 For more see [[file:config/rtags.org][rtags.org]].
 #+BEGIN_SRC emacs-lisp
	 (use-package rtags
		 :ensure t
		 :config
		 (progn
			 (setq rtags-path "~/.emacs.d/rtags/build/bin")
			 (unless (rtags-executable-find "rc") (error "Binary rc is not installed!"))
			 (unless (rtags-executable-find "rdm") (error "Binary rdm is not installed!"))

			 (define-key c-mode-base-map (kbd "M-.") 'rtags-find-symbol-at-point)
			 (define-key c-mode-base-map (kbd "M-,") 'rtags-find-references-at-point)
			 (define-key c-mode-base-map (kbd "M-?") 'rtags-display-summary)
			 (rtags-enable-standard-keybindings)

			 (setq rtags-use-helm t)
			 ;; Shutdown rdm when leaving emacs.
			 (add-hook 'kill-emacs-hook 'rtags-quit-rdm)
			 (add-hook 'c-mode-hook 'rtags-start-process-unless-running)
			 (add-hook 'c++-mode-hook 'rtags-start-process-unless-running)
			 (add-hook 'objc-mode-hook 'rtags-start-process-unless-running)))
 #+END_SRC
 #+BEGIN_SRC emacs-lisp
	 ;; TODO: Has no coloring! How can I get coloring?
	 (use-package helm-rtags
		 :requires helm rtags
		 :ensure t
		 :config
		 (progn
			 (setq rtags-display-result-backend 'helm)))
 #+END_SRC
 #+BEGIN_SRC emacs-lisp
	 ;; Use rtags for auto-completion.
	 (use-package company-rtags
		 :requires company rtags
		 :ensure t
		 :config
		 (progn
			 (setq rtags-autostart-diagnostics t)
			 (rtags-diagnostics)
			 (setq rtags-completions-enabled t)
			 (push 'company-rtags company-backends)
			 ))
 #+END_SRC
 #+BEGIN_SRC emacs-lisp
	 ;; Live code checking.
	 (use-package flycheck-rtags
		 :requires flycheck rtags
		 :ensure t
		 :config
		 (progn
			 ;; ensure that we use only rtags checking
			 ;; https://github.com/Andersbakken/rtags#optional-1
			 (defun setup-flycheck-rtags ()
				 (flycheck-select-checker 'rtags)
				 (setq-local flycheck-highlighting-mode nil) ;; RTags creates more accurate overlays.
				 (setq-local flycheck-check-syntax-automatically nil)
				 (rtags-set-periodic-reparse-timeout 2.0)  ;; Run flycheck 2 seconds after being idle.
				 )
			 (add-hook 'c-mode-hook #'setup-flycheck-rtags)
			 (add-hook 'c++-mode-hook #'setup-flycheck-rtags)))
 #+END_SRC


* Code browser
ECB - The Emacs code browser.
For more information, see http://ecb.sourceforge.net/.
#+BEGIN_SRC emacs-lisp
	(use-package "ecb"
		:ensure t )
#+END_SRC

* Finding files
The following commands will help you when locating files.
Use =M-x= to run a command in Emacs.
    - find-file :: Opens up a file buffer
									 ( =C-x C-f= )
		- find-dired :: Opens up a directory buffer.
		- find-name-dired :: Finds files matching a pattern.
		- find-grep-dired :: Finds files containing a pattern.

In any of the =dired= buffers you can perform certain actions.
For example to start a =query-replace-regexp=, hit the =Q= key.

For more information, hit =?= inside any =dired= buffer.
And =h= for more advanced help.

* Spell checker
#+BEGIN_SRC emacs-lisp
	(use-package "flycheck" :ensure t
		:diminish flycheck-mode
		:diminish flyspell-mode)
#+END_SRC
* Flash cards
Pamparam provides a flashcard engine for org documents.
For more details see [[file:config/pamparam.org][pamparam.org]].
#+BEGIN_SRC emacs-lisp
	(use-package "pamparam"
		:ensure t
		:init
		(setq pamparam-path "~/.emacs.d/flashcards.pam")
		(rjh/load-config "pamparam.org"))
#+END_SRC

* Authentication
=oauth= package.
Mainly for Google authentication.
#+BEGIN_SRC emacs-lisp
	(use-package "oauth2" :ensure t)
#+END_SRC

Pinentry for gpg-agent
#+BEGIN_SRC emacs-lisp
	(use-package "pinentry" :ensure t)
#+END_SRC
Please ensure the following setting is enabled for =~/.gnupg/gpg-agent.conf=.
	#+BEGIN_EXAMPLE
	allow-emacs-pinentry
	#+END_EXAMPLE
This is [[https://www.gnu.org/software/emacs/manual/html_mono/epa.html#fnd-1][required]] for GnuPG 2.1.5 or later; if you do not use a graphical
=pinentry= program.

* Ledger
Ledger is a cli accounting system.
See [[https://www.ledger-cli.org/3.0/doc/ledger-mode.html][here]] for more details.
#+BEGIN_SRC emacs-lisp
		(use-package "ledger-mode"
			:ensure t
			:init
			(add-to-list 'auto-mode-alist '("\\.ledger$" . ledger-mode))
	)
#+END_SRC


* Mutt
This file provides integration with mutt.
For more see [[file:config/mutt.org][mutt.org]]
#+BEGIN_SRC emacs-lisp
	(rjh/load-config "mutt.org")
#+END_SRC

* Address-book
BBDB, The insidious big brother database.
#+BEGIN_SRC emacs-lisp
	(use-package bbdb
		:ensure t
		:init
		(require 'bbdb)
		(setq bbdb-file "~/.bbdb/bbdb"
					bbdb-phone-style nil)
		(bbdb-initialize 'message)
		(bbdb-insinuate-message)
		)
#+END_SRC

BBDB vcard import/export.
Use =bbdb-vcard-import-file= to import a vcard file.
And =bbdb-vcard-export-file= to export a vcard file.
#+BEGIN_SRC emacs-lisp
	(use-package bbdb-vcard
	  :requires bbdb
		:ensure t
		:init
		(require 'bbdb-vcard)
		(setq bbdb-vcard-directory "~/.bbdb"))
#+END_SRC

* Calendar
 Calfw - The pretty Calendar
For more information see the configuration file, [[file:config/calfw.org][calfw.org]].
	#+BEGIN_SRC emacs-lisp
		(use-package "calfw"
			:ensure t
			:init
			(rjh/load-config "calfw.org")
			:bind ("C-x a c" . rjh/two-week-view))

		(use-package "calfw-org"
			:ensure t
			:init
			(require 'calfw-org)
			(setq cfw:org-overwrite-default-keybinding t)) ;; Org-mode like keybindings

		(use-package "calfw-ical"
			:ensure t
			:init
			(require 'calfw-ical))

		(use-package "calfw-cal"
			:ensure t
			:init
			(require 'calfw-cal))
	#+END_SRC

Diary mode configuration.
For more details see [[file:config/diary.org][diary.org]].
#+BEGIN_SRC emacs-lisp
	(rjh/load-config "diary.org")
#+END_SRC

* Emacs lisp
An api for working with files in Emacs lisp.
( https://github.com/rejeep/f.el )
#+BEGIN_SRC emacs-lisp
	(use-package "f" :ensure t )
#+END_SRC

* MULE
Multi-lingual environment for Emacs.
For more see [[file:config/mule.org][mule.org]]
#+BEGIN_SRC emacs-lisp
	(set-language-environment "Japanese")
	(load-library "anthy")
#+END_SRC

Font correction.
#+BEGIN_SRC emacs-lisp
	(defun rjh/font-correction ()
		(set-fontset-font
		 (frame-parameter nil 'font)
		 'japanese-jisx0208
		 '("Sazanami Gothic" . "unicode-bmp")))
	(if (daemonp)
			'()
		(rjh/font-correction))
#+END_SRC

* Workgroups
Workgroups provides defined layouts for Emacs.
( https://github.com/tlh/workgroups.el )
 #+BEGIN_SRC emacs-lisp
	 (use-package "workgroups"
		 :init
		 (require 'workgroups)
		 (workgroups-mode 1)
		 (setq wg-prefix-key (kbd "C-c w"))
		 (wg-load "~/.emacs.d/workgroups" )
		 :ensure t )
 #+END_SRC

Keybindings:
Use the following with <prefix> ;
   + C-c w :: <prefix>
   + c :: wg-create-workgroup
	 + A :: wg-rename-workgroup
	 + v :: wg-switch-to-workgroup
	 + n/p :: next/prev workgroup
	 + 0-9 :: switch thru positions in list
	 + w :: wg-toggle-morph (animation)
	 + C-s/l :: save / load workgroup
   + k :: kill workgroup
   + ,/. :: move left/right in group listing
	 + ? :: wg-help

* Themes
Use the =diff-hl= package to highlight changed-and-uncommitted lines when
programming.
#+BEGIN_SRC emacs-lisp
	(use-package diff-hl
		:ensure t
		:init
		(require 'diff-hl)
		(add-hook 'prog-mode-hook 'turn-on-diff-hl-mode)
		(add-hook 'vc-dir-mode-hook 'turn-on-diff-hl-mode))
#+END_SRC

For more on themes, checkout [[file:config/theme.org][theme.org]].
#+BEGIN_SRC emacs-lisp
	(use-package "material-theme" :ensure t )
	(use-package "solarized-theme"
		:ensure t
		:config
		(defun hrs/apply-theme ()
			(setq solarized-use-variable-pitch nil)
			(setq solarized-height-plus-1 1.0)
			(setq solarized-height-plus-2 1.0)
			(setq solarized-height-plus-3 1.0)
			(setq solarized-height-plus-4 1.0)
			(setq solarized-high-contrast-mode-line t)
			(load-theme 'solarized-dark t)))
	(use-package "fill-column-indicator" :ensure t )
	(rjh/load-config "theme.org")
#+END_SRC

Miscellaneous text options.
For more info see [[file:config/text.org][text.org]].
#+BEGIN_SRC emacs-lisp
	(rjh/load-config "text.org")
#+END_SRC

* Telephone line
A pretty message bar for Emacs.
( https://github.com/dbordak/telephone-line )
#+BEGIN_SRC emacs-lisp
	(use-package telephone-line
		:ensure t
		:config
		(rjh/load-config "telephone-line.org"))
;	 :init
	(require 'telephone-line)
	(telephone-line-mode 1)
#+END_SRC

* Abbrev
Abbreviation configuration.
For more see [[file:config/abbrev.org][abbrev.org]].
#+BEGIN_SRC emacs-lisp
	(rjh/load-config "abbrev.org")
#+END_SRC
* Fonts
Setup font functions, mostly courtesy of Harry Schwartz.
For more see [[file:config/fonts.org][fonts.org]].
#+BEGIN_SRC emacs-lisp
	(rjh/load-config "fonts.org")
#+END_SRC

* Backups
Setup file backup behaviour for Emacs.
For more see [[file:config/backup.org][backup.org]].
#+BEGIN_SRC emacs-lisp
	(rjh/load-config "backup.org")
#+END_SRC

* Undo tree
By default =C-/= will undo.
Now =C-S-/= will redo.
=C-x u= will provide a visual undo tree which can be navigated with the arrow
keys. Type =q= to exit.

See [[http://pragmaticemacs.com/emacs/advanced-undoredo-with-undo-tree/][here]] for examples.
#+BEGIN_SRC emacs-lisp
	(use-package "undo-tree"
		:ensure t
		:init
		(global-undo-tree-mode 1)
		(defalias 'redo 'undo-tree-redo)
		(global-set-key (kbd "C-S-/") 'redo))
#+END_SRC

* Recentf
Save recent files list between sessions.

Enable recentf-mode, set max items, set keybinding.
#+BEGIN_SRC emacs-lisp
	(recentf-mode 1)
	(setq recentf-max-menu-items 100)
	(global-set-key "\C-x\ \C-r" 'recentf-open-files)
#+END_SRC

Save recent files every 5 minutes.
#+BEGIN_SRC emacs-lisp
	(run-at-time nil (* 5 60) 'recentf-save-list)
#+END_SRC

* Numbers
Methods for manipulating numbers in Emacs.
For more details see [[file:config/numbers.org][numbers.org]]
#+BEGIN_SRC emacs-lisp
	(rjh/load-config "numbers.org")
#+END_SRC

Keybindings
#+BEGIN_SRC emacs-lisp
	(global-set-key (kbd "M-+") 'my-increment-number-decimal)
	(global-set-key (kbd "M-_") 'my-decrement-number-decimal)
	(global-set-key (kbd "C-M-+") 'my-increment-number-hexadecimal)
	(global-set-key (kbd "C-M-_") 'my-decrement-number-hexadecimal)
#+END_SRC
