#+TITLE: README for Emacs configuration
#+AUTHOR: Roger J. H. Welsh
#+email: rjhwelsh@gmail.com

* What is this?
This a blanked version of my own personal configuration for Emacs.

* Installation Instructions
To install the emacs.d setup, you will need to do the following.
These instructions, assume you will clone the repo to =~/emacs.d= .
*You can clone directly to your .emacs.d directory, but this is not recommended.*

Set the following locations as variables; note these *will* be different on
Windows.
#+BEGIN_SRC sh
export LOCALREPO=~/emacs.d
export CONFIGDIR=~/.emacs.d
#+END_SRC

Clone my repository.
#+BEGIN_SRC sh
git clone https://github.com/rjhwelsh/emacs.d $LOCALREPO
#+END_SRC

Create the .emacs.d config directory (if it does not exist).
#+BEGIN_SRC sh
mkdir -vp $CONFIGDIR
#+END_SRC

Copy over essential configuration options, and create base directories for
(some) modules.
#+BEGIN_SRC sh
cp -v $LOCALREPO/{init.el,configuration.org,personal.org,workgroups,agenda-files} $CONFIGDIR
mkdir -vp $CONFIGDIR/{org,snippets}
#+END_SRC

Make sure that =configuration.org= in the =$CONFIGDIR= uses the correct
loadpath; based on the location of =$LOCALREPO=. Open this in your
second-favourite editor and fix "~/emacs.d" to be the same as your $CONFIGDIR.

#+BEGIN_EXAMPLE file:configuration.org
122 * Configuration modules
123
124
125 #+BEGIN_SRC emacs-lisp
126 (setq rjh/local-config-repo "~/emacs.d")
127 #+END_SRC
#+END_EXAMPLE

After setting up any additional dependencies from below, starting up emacs will
automatically download and install packages from melpa according to the default
configuration.

* Dependencies
You will have to manually install these packages in order to be able to use my
configuration. Please see the list below.

 * [[https://github.com/hrs][Harry R. Schwartz's]] , [[https://github.com/hrs/sensible-defaults.el][sensible-defaults.el]].

#+BEGIN_SRC sh
git clone https://github.com/hrs/sensible-defaults.el ~/sensible-defaults.el
cp -v ~/sensible-defaults.el/sensible-defaults.el ~/.emacs.d/sensible-defaults.el
#+END_SRC


* Configuration
The =configuration.org= in your .emacs.d (emacs config) directory, acts as the
centre of operations for adjusting your configuration.

Adding/removing config options from the =Configuraton Modules= section, will
selectively load/not-load parts of my configuration that you like/dislike.

Each configuration is specified as an org-file that you may load using the
=rjh/load-config-modules= variable.

For example, to only load my =org.org= and =git.org= configuration modules, simply
change the variable to only include these in =configuration.org=.
Lines can also be commented out using =;= , as in =; "evil.org"=.

#+BEGIN_SRC emacs-lisp
	(setq rjh/load-config-modules '(
			"org.org"
			"git.org"
		 ; "evil.org"
	))
#+END_SRC

You can even write your own modules, and put them in the load-path.
If you have any =org= modules for configuration that you would like to submit,
please submit a pull-request.

The main goal of this project is to provide documented configuration, to quickly
get a newbie to emacs up and running quickly. Modules should stand alone, and be
set up for a particular purpose.

* Extra notes
 * If git is not installed on your system, you may get some errors when you
   start-up; comment out the =git= module in =configuration.org= to fix.
