#+TITLE: README for Emacs configuration
#+AUTHOR: Roger J. H. Welsh
#+email: rjhwelsh@gmail.com

* What is this?
This a blanked version of my own personal configuration for Emacs.
* Dependencies
** Emacs Version
 Emacs version 24.5 or higher is required.
** Sensible-defaults.el
 You will have to manually install Harry's package below in order to be able to use my
 configuration.

	* [[https://github.com/hrs][Harry R. Schwartz's]] , [[https://github.com/hrs/sensible-defaults.el][sensible-defaults.el]].

 Install instructions.
 #+BEGIN_SRC sh
 git clone https://github.com/hrs/sensible-defaults.el ~/sensible-defaults.el
 cp -v ~/sensible-defaults.el/sensible-defaults.el ~/.emacs.d/sensible-defaults.el
 #+END_SRC

** org-gantt.el
The org-gantt.org module depends on org-gantt.el.
 * [[https://github.com/swillner/org-gantt]] , [[https://github.com/swillner/org-gantt/blob/master/org-gantt.el][org-gantt.el]]

Install instructions.
#+BEGIN_SRC sh
git clone https://github.com/swillner/org-gantt ~/org-gantt
cp -v ~/org-gantt/org-gantt.el ~/.emacs.d/org-gantt.el
#+END_SRC

* Installation
To install the emacs.d setup, you will need to do the following.
These instructions, assume you will clone the repo to =~/emacs.d= .
*You can clone directly to your .emacs.d directory, but this is not recommended.*

** basic config setup
 Set the following locations as variables; note these *will* be different on
 Windows.
 #+BEGIN_SRC sh
 export LOCALREPO=~/emacs.d
 export CONFIGDIR=~/.emacs.d
 #+END_SRC

 Clone my repository.
 #+BEGIN_SRC sh
 git clone https://github.com/rjhwelsh/emacs.d $LOCALREPO
 #+END_SRC

 Create the .emacs.d config directory (if it does not exist).
 #+BEGIN_SRC sh
 mkdir -vp $CONFIGDIR
 #+END_SRC

 Copy over essential configuration options, and create base directories for
 (some) modules.
 #+BEGIN_SRC sh
 cp -v $LOCALREPO/{init.el,configuration.org,personal.org,workgroups,agenda-files} $CONFIGDIR
 mkdir -vp $CONFIGDIR/{org,snippets}
 #+END_SRC


** personal.org - Required config
*** rjh/load-config-repo
	Make sure that =personal.org= in the =$CONFIGDIR= uses the correct
	load-config-repo; i.e. the location of your =$LOCALREPO=.

	Open this in your second-favourite editor and fix "~/emacs.d" to be the same as
	your $CONFIGDIR.
	#+BEGIN_EXAMPLE file:
	(setq rjh/local-config-repo "~/emacs.d") ; Set to $CONFIGDIR
	#+END_EXAMPLE

*** hrs/default-font
	You will also need to select a font.
	I like to use Hermit, but it is not all that common.
	Change "Hermit" to your preferred system font. (Like "DejaVuSans", or "Inconsolata")

	#+BEGIN_EXAMPLE file:personal.org
	(setq hrs/default-font "Hermit")
	#+END_EXAMPLE

	After setting up any additional dependencies from below, starting up emacs will
	automatically download and install packages from melpa according to the default
	configuration.

* Configuration

** configuration.org
 The =configuration.org= in your .emacs.d (emacs config) directory, acts as the
 centre of operations for adjusting your configuration.

 Adding/removing config options from the =Configuraton Modules= section, will
 selectively load/not-load parts of my configuration that you like/dislike.

 Each configuration is specified as an org-file that you may load using the
 =rjh/load-config-modules= variable.

 For example, to only load my =org.org= and =git.org= configuration modules, simply
 change the variable to only include these in =configuration.org=.
 Lines can also be commented out using =;= , as in =; "evil.org"=.

 #+BEGIN_SRC emacs-lisp
	 (setq rjh/load-config-modules '(
			 "org.org"
			 "git.org"
			; "evil.org"
	 ))
 #+END_SRC

 You can even write your own modules, and put them in the load-path.
 If you have any =org= modules for configuration that you would like to submit,
 please submit a pull-request.

 The main goal of this project is to provide documented configuration, to quickly
 get a newbie to emacs up and running quickly. Modules should stand alone, and be
 set up for a particular purpose.

** personal.org
Use =personal.org= in your .emacs.d (emacs config) directory for all your
personal configuration. Personal configuration, is anything you might want to
keep private and separate from the rest of your config.

I created this so that I could share the joys of my config file, without being
loose with my own personal details. It also serves well as a config file for
matters of personal taste (Chrome, Firefox, IE, for example).

The file is mostly self-explanatory. use it to setup variables describing:
 1. Your name
 2. email address
 3. Calendar location
 4. Contact Information
 5. Default font
 6. Default web-browser

* Updating
To update configuration modules from my repo, use a git pull.
#+BEGIN_EXAMPLE sh
cd $LOCALREPO
git pull
#+END_EXAMPLE

* Extra notes
 * If git is not installed on your system, you may get some errors when you
   start-up; comment out the =git= module in =configuration.org= to fix.
* Further Reading
The emacs tutorial and info pages are a useful resource.
 =C-h t= and =C-h i= respectively.

The following emacs configurations, provided inspiration, and useful content.
			 1. [[https://github.com/hrs/dotfiles/blob/master/emacs/.emacs.d/configuration.org][Harry Schwartz's config]]
			 2. [[https://ogbe.net/emacsconfig.html][Dennis Ogbe Emacs config]]
			 3. [[http://doc.norang.ca/org-mode.html][Bernt Hansen comprehensive org]]
			 4. [[http://pages.sachachua.com/.emacs.d/Sacha.html][Sacha Chua's Emacs config]]

And don't forget to checkout the emacs wiki.
 - https://www.emacswiki.org/

May the lisp be with you.
