#+TITLE: Emacs configuration
#+AUTHOR: Roger J. H. Welsh
#+email: rjhwelsh@gmail.com

* What is this?
This a blanked version of my configuration files for Emacs.
 - Configuration can be selectively loaded through a customization setting.
 - Or by specifying it through an environmental variable.

Or rather my messy notes on Emacs configuration. ;)

Packages are usually setup to be automatically installed through elpa,
melpa or melpa-stable, mainly with [[https://github.com/jwiegley/use-package][use-package]].

* Before you start
** Emacs Version
   This configuration was tested on Emacs 27.0.

** Some configuration settings depend on 3rd party applications
   This should be noted in the specific configuration org file.
   Some examples, include sensible-defaults, zetteldeft, org-gantt and jdee-server.

** Setup script
A setup script is provided for quick installation on linux.

*Warning! This may overwrite your current emacs.d configuration files*

   #+begin_src sh
./setup.sh --help # Show help 
./setup.sh --install # Install base configuration, link to repository
./setup.sh --install-deps # Install some third-party applications (elisp only)
   #+end_src

* Installation
** Quick install on Linux
Clone the repository to your desired location and run =./setup.sh=.
The install process will symlink =~/.emacs.d/rjh= to =$LOCALREPO=.

*Warning! This may overwrite your current emacs.d configuration files*
#+BEGIN_SRC sh
 export LOCALREPO=~/rjh.emacs.d/
 git clone https://github.com/rjhwelsh/emacs.d $LOCALREPO &&
 cd $LOCALREPO &&
 ./setup.sh -i
#+END_SRC

** Manual install
This install deviates from =setup.sh= slightly, but it should work for most systems.
Report an issue if it doesn't.

Clone repository.
   #+begin_example sh
git clone https://github.com/rjhwelsh/emacs.d ~/.emacs.d/rjh # clone repository
   #+end_example

If you have cloned the repository to an alternative location, copy over rjh.el.
This will prompt for customization options on startup. 
#+begin_example sh
mkdir -v ~/.emacs.d/rjh &&
cp -v ~/$ALTERNATE_LOCATION/rjh.el ~/.emacs.d/rjh/rjh.el             # add rjh.el
#+end_example

Replace init.el in your =.emacs.d= directory with the one from the repository.
   #+begin_example sh
cp -v ~/.emacs.d/rjh/init.el ~/.emacs.d/init.el              # replace init.el
   #+end_example

Create some blank files, and base directories that should exist, for
default configuration to work.
#+begin_example sh
 mkdir -vp ~/.emacs.d/{org,snippets,private}
 touch ~/.emacs.d/agenda-files
#+end_example

* Loading configuration segments
** init directory
A list of browsable org-files which are sourced for configuration are
available in the [[file:init][init]] directory. Each org-file represents
configuration for a particular Emacs application.

Use =M-x rjh/load= to load a configuration file in Emacs. Pressing
=<TAB>= will auto-complete to an available option.

Use =M-x rjh/save= to save a configuration file, to automatically load
the next time you start Emacs.

Use =M-x rjh/edit= to edit a configuration file, this will open the
org-file for editing.

Each configuration has a *post-fix* =:init= or =:private=.
 - =:init= :: refers to configuration provided from my repository.
 - =:private= :: refers to configuration that should be kept separate for privacy reasons. 

For example, =djcb/mu4e:init= is configuration available in the [[file:init/djcb/mu4e.org][init]]
directory.  

/=rjh.el= allows you to change the location of =init= and
=private= directories through customization variables/

** private directory
Private configuration is used in the same way as the init configuration previous.

Blank configuration templates are available in the [[file:private][private]] directory.  
Copy them over to =~/.emacs.d/private/= and they will be available for loading. 

You can also create your own org-file configuration, and add it to this location.

** environment variables
Environment variables can be set to load a particular sequence of configuration.

/Leave out the configuration *post-fix* when using environment variables./

The current options are: 
    - EMACS_CONFIG :: Loads configuration from the =init= directory,
      and then from the =private= directory
    - EMACS_CONFIG_PRIVATE :: Loads configuration from =private=
      directory only

For example, this loads extra configuration for mu4e; 
#+begin_example sh
/usr/bin/env EMACS_CONFIG="djcb/mu4e emacs/smtpmail" /usr/bin/emacs
#+end_example

Customization configuration, set using =rjh/save= or
=rjh/save-custom=, is loaded after any environment variable
configurations.

Environment variables allow for breaking up and testing different and
sometimes incompatible configuration options.

* Issues
** Gnu elpa key-ring update
The first time updating the package repositories, you may need to
udate the gnu-elpa-keyring manually.  

See [[https://elpa.gnu.org/packages/gnu-elpa-keyring-update.html][gnu-elpa-keyring-update]] for info.

Using bash and gnupg.
#+begin_src sh
gpg --homedir ~/.emacs.d/elpa/gnupg --receive-keys 066DAFCB81E42C40
gpg --homedir ~/.emacs.d/elpa/gnupg \
          --quick-set-expire 474F05837FBDEF9B 1y
#+end_src

Alternatively, you can turn signature-verification off.
#+begin_src emacs-lisp
(setq package-check-signature nil)
#+end_src

* Some reference configurations
The emacs tutorial and info pages are a useful resource.
 =C-h t= and =C-h i= respectively.

The following emacs configurations, provided inspiration, and useful content.
    1. [[https://github.com/hrs/dotfiles/blob/master/emacs/.emacs.d/configuration.org][Harry Schwartz's config]]
    2. [[https://ogbe.net/emacsconfig.html][Dennis Ogbe Emacs config]]
    3. [[http://doc.norang.ca/org-mode.html][Bernt Hansen comprehensive org]]
    4. [[http://pages.sachachua.com/.emacs.d/Sacha.html][Sacha Chua's Emacs config]]

And don't forget to checkout the emacs wiki.
 - https://www.emacswiki.org/

All the best!
