#+TITLE: Calendar configuration and packages
#+AUTHOR: Roger J. H. Welsh
#+EMAIL: rjhwelsh@gmail.com
#+PROPERTY: header-args    :results silent
#+STARTUP: content

* Google Calendar / Caldav integration
#+BEGIN_SRC emacs-lisp
		;; Google Calendar Integration
		;; Try using package org-caldav
		(use-package "oauth2" :ensure t)
		(use-package "org-caldav" :ensure t)
#+END_SRC
* Calfw - The pretty Calendar
This provides a very fancy calendar, which can be used in conjunction with
org-agendas, ics files and more. More information can be found [[https://github.com/kiwanami/emacs-calfw][here]].
** Packages
 Initial setup.
 #+BEGIN_SRC emacs-lisp
	 ;; Pretty Calendar
	 (use-package "calfw" :ensure t )
	 (use-package "calfw-org" :ensure t
		:init
		(setq cfw:org-overwrite-default-keybinding t) ;; org-mode like keybindings
	 )
	 (use-package "calfw-ical" :ensure t )
	 (use-package "calfw-cal" :ensure t )
 ;	(use-package "calfw-howm" :ensure t )
	 (require 'calfw-cal)
	 (require 'calfw-ical)
	 (require 'calfw-org)
 ;  (require 'calfw-howm)
 #+END_SRC

** Unicode
 Setup for unicode.
 #+BEGIN_SRC emacs-lisp
	 ;; Unicode characters
	 (setq cfw:fchar-junction ?╋
				 cfw:fchar-vertical-line ?┃
				 cfw:fchar-horizontal-line ?━
				 cfw:fchar-left-junction ?┣
				 cfw:fchar-right-junction ?┫
				 cfw:fchar-top-junction ?┯
				 cfw:fchar-top-left-corner ?┏
				 cfw:fchar-top-right-corner ?┓
			 cfw:render-line-breaker 'cfw:render-line-breaker-none
			 )

 #+END_SRC

** Examples
 A demonstration calendar is in the example below.
 #+BEGIN_EXAMPLE
 (defun my-open-calendar ()
   (interactive)
   (cfw:open-calendar-buffer
		:contents-sources
		(list
     (cfw:org-create-source "Green")  ; orgmode source
     (cfw:howm-create-source "Blue")  ; howm source
     (cfw:cal-create-source "Orange") ; diary source
     (cfw:ical-create-source "Moon" "~/moon.ics" "Gray")  ; ICS source1
     (cfw:ical-create-source "gcal" "https://..../basic.ics" "IndianRed") ; google calendar ICS
		)))
 #+END_EXAMPLE

 Fancy Grid settings; various examples.
 #+BEGIN_EXAMPLE
 ;; Default setting
 (setq cfw:fchar-junction ?+
       cfw:fchar-vertical-line ?|
       cfw:fchar-horizontal-line ?-
       cfw:fchar-left-junction ?+
       cfw:fchar-right-junction ?+
       cfw:fchar-top-junction ?+
       cfw:fchar-top-left-corner ?+
       cfw:fchar-top-right-corner ?+ )

 ;; Unicode characters
 (setq cfw:fchar-junction ?╋
       cfw:fchar-vertical-line ?┃
       cfw:fchar-horizontal-line ?━
       cfw:fchar-left-junction ?┣
       cfw:fchar-right-junction ?┫
       cfw:fchar-top-junction ?┯
       cfw:fchar-top-left-corner ?┏
       cfw:fchar-top-right-corner ?┓)

 ;; Another unicode chars
 (setq cfw:fchar-junction ?╬
       cfw:fchar-vertical-line ?║
       cfw:fchar-horizontal-line ?═
       cfw:fchar-left-junction ?╠
       cfw:fchar-right-junction ?╣
       cfw:fchar-top-junction ?╦
       cfw:fchar-top-left-corner ?╔
       cfw:fchar-top-right-corner ?╗)
 #+END_EXAMPLE

** Calendar Views

Keybinding
#+BEGIN_SRC emacs-lisp
(global-set-key (kbd "C-x a c") 'rjh/two-week-view)
#+END_SRC

Two week agenda.
 #+BEGIN_SRC emacs-lisp
			(defun rjh/two-week-view ()
				(interactive)
				(cfw:open-calendar-buffer
				 :contents-sources
			   ( rjh/calendar-sources ); set this var in personal.org
				 :view
				 'two-weeks
				 ))
 #+END_SRC
Week agenda.
 #+BEGIN_SRC emacs-lisp
			(defun rjh/week-view ()
				(interactive)
				(cfw:open-calendar-buffer
				 :contents-sources
			   ( rjh/calendar-sources ) ; set this var in personal.org
				 :view
				 'week
				 ))
 #+END_SRC

* Emacs diary integration
Set diary file
#+BEGIN_SRC emacs-lisp
(setq rjh/diary diary-file ) ;; I just use the default diary for my appointments )
#+END_SRC

Calendar style. Diary entries. Diary file.
Use iso by default.
#+BEGIN_SRC emacs-lisp
(setq calendar-date-style 'iso
diary-number-of-entries 1
diary-file rjh/diary
)
;; In-case calendar is already loaded..
(calendar-set-date-style 'iso)

#+END_SRC

Holidays display.
Most of them are American and I now source holidays from a google.ics.
Remove all holiday data.
#+BEGIN_SRC emacs-lisp
(setq calendar-holidays nil)
#+END_SRC

Reminders
#+BEGIN_SRC emacs-lisp
(appt-activate)
#+END_SRC

Integrate with org-mode
#+BEGIN_SRC emacs-lisp
(setq org-agenda-include-diary t)
#+END_SRC

Sort entries hook.
#+BEGIN_SRC emacs-lisp
(add-hook 'diary-list-entries-hook 'diary-sort-entries t)
#+END_SRC
