* desktop.el
 Save the Desktop, i.e.,
	- some global variables
 	- the list of buffers with associated files.  For each buffer also
		- the major mode
		- the default directory
		- the point
		- the mark & mark-active
		- buffer-read-only
		- some local variables
	- frame and window configuration

 To use this, use customize to turn on desktop-save-mode or add the
 following line somewhere in your init file:

 #+begin_example emacs-lisp
   (desktop-save-mode 1)
 #+end_example

 For further usage information, look at the section
 (info "(emacs)Saving Emacs Sessions") in the GNU Emacs Manual.

** Auto-save
Does not ask to save.
   #+begin_src emacs-lisp
     (setq desktop-save t)
   #+end_src

** Frame settings
Restores frames into current display.
   #+begin_src emacs-lisp
     (setq 
      desktop-restore-frames t
      desktop-restore-in-current-display t
      desktop-restore-forces-onscreen t
      desktop-restore-reuses-frames nil
      desktop-save-buffer t
      )
   #+end_src

** Multiple desktops hack
Use session_state to identify session.
   #+begin_src emacs-lisp
     ;; Session identification
     (rjh/use "rjh/session_state:init")

     (setq 
      desktop-base-file-name (session-state-save-path "desktop")
      desktop-base-lock-name (session-state-save-path "desktop.lock")
      )
   #+end_src

** Enable desktop save mode
Only enable desktop mode, if Emacs is NOT running as a daemon.
 #+begin_src emacs-lisp
   (unless (daemonp) (desktop-save-mode 1))
 #+end_src

** Troubleshooting notes
   If using =emacs/desktop= and =wedler/session= at the same time, ensure that =wedler/session= is loaded first.

